import type { Metadata } from 'next';
import './globals.css';

import ProviderWrapper from './ProviderWrapper';
import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactElement;
}) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          <StoreProvider>{children}</StoreProvider>
        </ProviderWrapper>
      </body>
    </html>
  );
}
