import '@/app/globals.css';

import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Provider from '@/app/providers';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'bg-accent/20')}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
